backend:
  name: github
  repo: luccasavila/luccasavila.dev
  branch: master
  site_domain: luccasavila.dev
media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow
collections:
  - name: projects
    label: projetos
    folder: content/projects
    create: true
    slug: '{{slug}}'
    fields:
      - { name: 'layout', label: 'Layout', widget: 'select', options: ['project', 'post'] }
      - { name: 'title', label: 'Title', widget: 'string', required: true }
      - { name: 'description', label: 'Description', widget: 'string' }
      - { name: 'link', label: 'Website Link', widget: 'string' }
      - { name: 'featuredImage', label: 'Thumbnail', widget: 'image', required: true}
      - { name: 'tags', label: 'Tags', widget: 'list', default: [''] }
      - { name: 'body', label: Body, widget: 'markdown' }
